backend:
  name: git-gateway
  branch: master

media-folder: "Static/img"
public-folder: "Static"

collections:
  - name: "Blog"
    label: "Blog"
    folder: "Static"
    create: true
    slug: "{{year}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Rating (scale of 1-5)", name: "rating", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }
